// sveltekit/src/routes/fetch/+page.svelte
<script lang="ts">
	import LinkComponent from '$components/LinkComponent.svelte';
	import { getFetchData } from './data.remote';

	const query = getFetchData();
</script>

<div class="absolute top-5 left-3">
	<LinkComponent to="/">Home</LinkComponent>
</div>
<div class="h-screen w-screen bg-zinc-800">
	<div class="flex h-full flex-col items-center justify-center">
		<h1 class="text-center text-4xl font-bold text-orange-400">Fetch data</h1>
		{#if query.loading}
			<div class="m-5 text-white">Loading...</div>
		{:else if query.error}
			<div class="m-5 text-white">Error: {query.error.message}</div>
		{:else}
			<div class="m-5 text-white">
				<h2>Name: {query.current?.name}</h2>
				<p>Email: {query.current?.email}</p>
				<p>Age: {query.current?.age}</p>
				<p>Phone: {query.current?.phone}</p>
				<p>Address: {query.current?.address}</p>
			</div>
		{/if}
	</div>
</div>

// nuxt/app/pages/fetch/index.vue
<script setup lang="ts">
import type { UserData } from "~~/server/api/datafetch.get";

const {
	data: user,
	error,
	pending,
} = useFetch<UserData>("/api/datafetch", { lazy: true });
</script>

<template>
	<div class="absolute top-5 left-3">
		<LinkComponent to="/">Home</LinkComponent>
	</div>
	<div class="bg-zinc-800 w-screen h-screen">
		<div class="flex flex-col items-center justify-center h-full">
			<h1 class="text-green-400 text-center text-4xl font-bold">Fetch data</h1>
			<div v-if="pending" class="m-5 text-white">Loading...</div>
			<div v-else-if="!user" class="m-5 text-white">No data found</div>
			<div v-else class="m-5 text-white">
				<h2>Name: {{ user?.name }}</h2>
				<p>Email: {{ user?.email }}</p>
				<p>Age: {{ user?.age }}</p>
				<p>Phone: {{ user?.phone }}</p>
				<p>Address: {{ user?.address }}</p>
			</div>
		</div>
	</div>
</template>
